from enum import Enum


class Institution(Enum):
    GOVERNMENT = "Guvernul Romaniei"
    PARLIAMENT = "Parlamentul Romaniei "
    SENATE = "Senat"
    DEPUTIES_CHAMBER = "Camera Deputatilor"
    GENERAL_GOVERNMENT_SECRETARY = "Secretariatul General al Guvernului"
    PUBLIC_ADMIN_MINISTRY = "Ministerul Dezvoltarii Regionale si Administratiei Publice"
    ENVIRONMENT_MINISTRY = "Ministerul Mediului"
    INTERIOR_AFFAIRS_MINISTRY = "Ministerul Afacerilor Interne"
    EXTERIOR_AFFAIRS_MINISTRY = "Ministerul Afacerilor Externe"
    DEFENSE_MINSTRY = "Ministerul Apararii Nationale"
    FINANCES_MINISTRY = "Ministerul Finantelor Publice"
    JUSTICE_MINISTRY = "Ministerul Justitiei"
    AGRICULTURE_MINISTRY = "Ministerul Agriculturii si Dezvoltarii Rurale"
    EDUCATION_MINISTRY = "Ministerul Educatiei Nationale"
    LABOR_MINISTRY = "Ministerul Muncii si Justitiei Sociale "
    ECONOMY_MINISTRY = "Ministerul Economiei"
    ENERGY_MINISTRY = "Ministerul Energiei"
    TRANSPORTATION_MINISTRY = "Ministerul Transporturilor"
    EUROPEAN_FUNDS_MINISTRY = "Ministerul Fondurilor Europene"
    BUSINESS_MINISTRY = "Ministerul pentru Mediul de Afaceri,Comert si Antreprenoriat"
    HEALTH_MINISTRY = "Ministerul Sanatatii"
    CULTURE_MINISTRY = "Ministerul Culturii si Identitatii Nationale"
    FOREST_MINISTRY = "Ministerul Apelor si Padurilor"
    RESEARCH_MINISTRY = "Ministerul Cercetarii si Inovarii"
    COMMUNICATION_MINISTRY = "Ministerul Comunicatiilor si Societatii Informationale"
    YOUTH_MINISTRY = "Ministerul Tineretului si Sportului"
    TOURISM_MINISTRY = "Ministerul Turismului"
    EVERYWHERE_MINISTRY = "Ministerul pentru Romanii de Pretutindeni"
    PARLIAMENT_MINISTRY = "Ministerul pentru Relatia cu Parlamentul"
    OTHER = "Alta Valoare"
