"""
Django settings for project_template project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

from .base import *

"""
If set Moonsheep won't communicate with PyBossa and will:
1. serve random mocked tasks
2. send form submissions straight to the verification
   won't test cross-checking as there is going to be only one entry, but will allow to test the whole flow  
"""
MOONSHEEP_DEVELOPMENT_MODE = True

DEBUG = TEMPLATE_DEBUG = True

INTERNAL_IPS = ['127.0.0.1', 'localhost']

AUTH_PASSWORD_VALIDATORS = []

MOONSHEEP_TASK_SOURCE = 'random'
MOONSHEEP_BASE_TASKS = ['project-template.tasks.TaskWithForm', 'project-template.tasks.TaskWithTemplate']

# Add debug toolbar
if DEBUG:
    INSTALLED_APPS += ['debug_toolbar', 'django_extensions']
    MIDDLEWARE.insert(1, 'debug_toolbar.middleware.DebugToolbarMiddleware')

SECRET_KEY = 'https://uploads.skyhighnetworks.com/wp-content/uploads/2015/08/06195203/Bart-Chalkboard-for-Blog-Post.png'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
