"""
Django settings for project_template project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

from .base import *

# TODO: describe crosscheck min entries
MOONSHEEP["MIN_ENTRIES_TO_CROSSCHECK"] = 1

DEBUG = TEMPLATE_DEBUG = True

INTERNAL_IPS = ["127.0.0.1", "localhost"]

AUTH_PASSWORD_VALIDATORS = []

# Add debug toolbar
if DEBUG:
    INSTALLED_APPS += ["debug_toolbar", "django_extensions"]
    MIDDLEWARE.insert(1, "debug_toolbar.middleware.DebugToolbarMiddleware")

# TODO: read it from env or generate a new one
SECRET_KEY = "https://uploads.skyhighnetworks.com/wp-content/uploads/2015/08/06195203/Bart-Chalkboard-for-Blog-Post.png"

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
